### ISSUE TITLE
Hangs on about screen

### ISSUE THREAD

**Issue by sjenkin** [EnviralDesign/GeoPix#13] opened 2021-04-13 12:21 UTC
**Describe the bug**
Hangs on the start screen, running on Macbook Pro under bootcamp

**To Reproduce**
1. Installed following the Readme file
2. Program runs and then can't get off the About Screen

**Expected behavior**
To run

**Screenshots**
![image](https://user-images.githubusercontent.com/32995730/114550827-39e06700-9c95-11eb-8fd7-c39201cf4fcf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, running on bootcamp on MBP 2017 i5 16gb ram

**Comment by EnviralDesign** [comment] 2021-04-13 18:58
Thanks for the report,

1) Are you able to click any of the buttons on the about screen? Home, donors, github, etc?
2) Are you clicking the X, or the darkened grey area around the about screen to close it?
3) Do you see any red error pings at the top bar (File, Tools, Help)?

You can also shift+escape to go to network mode, and check the textport for errors. try looking there while clicking the things that don't work.

Alternatively, if the issue is the UI just doesn't respond at all, there may be a deeper problem related to something else. I haven't tested on bootcamp / mbp setup personally so hard to perfectly recreate that on my end.

**Comment by sjenkin** [comment] 2021-04-14 00:58
1. Clicking those buttons does nothing, if I click "Load sample project" nothing seems to happen, but then you can start to hear some music
2. Clicking on the X is non- responsive
3. No red error pings
I will try the Shift+Escape and report back

Cheers

**Comment by EnviralDesign** [comment] 2021-04-14 02:51
roughly how long till you hear some music? Sounds like the software is loading and processing / working but you're just not seeing any UI updates after the initial one? 

Does anything change at all visually between clicking load sample project when the music starts?

**Comment by sjenkin** [comment] 2021-04-16 07:12
It is about 20-30 seconds before the music starts, but nothing changes visually and shift escape does open a different window but there is still nothing you can click or do.
I'll give up on bootcamp and install on a proper windows machine.

Cheers

**Comment by EnviralDesign** [comment] 2021-04-16 16:12
Think that's the best route - can't tell you more with out a similar setup, but sounds like rendering is freezing or something like that.

**Closed by EnviralDesign** 2021-04-16 16:12 UTC
